# Generated by Django 5.2.5 on 2026-02-15 09:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("issues", "0001_initial"),
        ("organizations", "0001_initial"),
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FieldDefinition",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Timestamp when the record was soft deleted",
                        null=True,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID4)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text='Field name (e.g., "Sprint", "Story Points")',
                        max_length=100,
                        verbose_name="name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Field description",
                        verbose_name="description",
                    ),
                ),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("text", "Single-line Text"),
                            ("textarea", "Multi-line Text"),
                            ("number", "Number"),
                            ("decimal", "Decimal"),
                            ("date", "Date"),
                            ("datetime", "Date & Time"),
                            ("select", "Select (Single)"),
                            ("multiselect", "Multi-select"),
                            ("checkbox", "Checkbox"),
                            ("user", "User Picker"),
                            ("url", "URL"),
                            ("email", "Email"),
                            ("labels", "Labels"),
                        ],
                        help_text="Type of field",
                        max_length=20,
                        verbose_name="field type",
                    ),
                ),
                (
                    "config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Field configuration (options, validation rules, etc.)",
                        verbose_name="configuration",
                    ),
                ),
                (
                    "default_value",
                    models.JSONField(
                        blank=True,
                        help_text="Default value for this field",
                        null=True,
                        verbose_name="default value",
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this field is required",
                        verbose_name="is required",
                    ),
                ),
                (
                    "placeholder",
                    models.CharField(
                        blank=True,
                        help_text="Placeholder text for UI",
                        max_length=255,
                        verbose_name="placeholder",
                    ),
                ),
                (
                    "help_text",
                    models.TextField(
                        blank=True,
                        help_text="Help text shown to users",
                        verbose_name="help text",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this field is active",
                        verbose_name="is active",
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        default=0, help_text="Display order", verbose_name="position"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="Organization this field belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="field_definitions",
                        to="organizations.organization",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "field definition",
                "verbose_name_plural": "field definitions",
                "db_table": "field_definitions",
                "ordering": ["organization", "position", "name"],
            },
        ),
        migrations.CreateModel(
            name="FieldContext",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Timestamp when the record was soft deleted",
                        null=True,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID4)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(
                        blank=True,
                        help_text="Override field required setting in this context",
                        null=True,
                        verbose_name="is required",
                    ),
                ),
                (
                    "is_visible",
                    models.BooleanField(
                        default=True,
                        help_text="Whether field is visible in this context",
                        verbose_name="is visible",
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Display order in this context",
                        verbose_name="position",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "issue_type",
                    models.ForeignKey(
                        blank=True,
                        help_text="Issue type this context applies to (null for all types)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="field_contexts",
                        to="issues.issuetype",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        help_text="Project this context applies to (null for all projects)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="field_contexts",
                        to="projects.project",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "field",
                    models.ForeignKey(
                        help_text="Field definition",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contexts",
                        to="fields.fielddefinition",
                    ),
                ),
            ],
            options={
                "verbose_name": "field context",
                "verbose_name_plural": "field contexts",
                "db_table": "field_contexts",
                "ordering": ["field", "project", "issue_type", "position"],
            },
        ),
        migrations.CreateModel(
            name="FieldScheme",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Timestamp when the record was soft deleted",
                        null=True,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID4)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Scheme name", max_length=100, verbose_name="name"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Scheme description",
                        verbose_name="description",
                    ),
                ),
                (
                    "field_configs",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Field-specific configurations for this project",
                        verbose_name="field configurations",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this scheme is active",
                        verbose_name="is active",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.OneToOneField(
                        help_text="Project this scheme belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="field_scheme",
                        to="projects.project",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "field scheme",
                "verbose_name_plural": "field schemes",
                "db_table": "field_schemes",
                "ordering": ["project"],
            },
        ),
        migrations.AddIndex(
            model_name="fielddefinition",
            index=models.Index(
                fields=["organization", "name"], name="field_defin_organiz_993423_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fielddefinition",
            index=models.Index(
                fields=["organization", "is_active"],
                name="field_defin_organiz_9260ae_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="fielddefinition",
            index=models.Index(
                fields=["organization", "field_type"],
                name="field_defin_organiz_afb493_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="fielddefinition",
            unique_together={("organization", "name")},
        ),
        migrations.AddIndex(
            model_name="fieldcontext",
            index=models.Index(
                fields=["field", "project"], name="field_conte_field_i_d90add_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fieldcontext",
            index=models.Index(
                fields=["field", "issue_type"], name="field_conte_field_i_5ec697_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fieldcontext",
            index=models.Index(
                fields=["project", "is_visible"], name="field_conte_project_fe0e66_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="fieldcontext",
            unique_together={("field", "project", "issue_type")},
        ),
        migrations.AddIndex(
            model_name="fieldscheme",
            index=models.Index(
                fields=["project", "is_active"], name="field_schem_project_943bfa_idx"
            ),
        ),
    ]
