# Generated by Django 5.2.5 on 2026-02-15 05:40

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Timestamp when the record was soft deleted",
                        null=True,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID4)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Project name", max_length=255, verbose_name="name"
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        db_index=True,
                        help_text="Unique project key (e.g., PROJ, BUG) - used in issue keys",
                        max_length=10,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Key must start with a letter and contain only uppercase letters and numbers",
                                regex="^[A-Z][A-Z0-9]{1,9}$",
                            )
                        ],
                        verbose_name="key",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Project description",
                        verbose_name="description",
                    ),
                ),
                (
                    "avatar",
                    models.URLField(
                        blank=True,
                        help_text="URL to project avatar/logo",
                        null=True,
                        verbose_name="avatar URL",
                    ),
                ),
                (
                    "project_type",
                    models.CharField(
                        choices=[
                            ("software", "Software"),
                            ("business", "Business"),
                            ("marketing", "Marketing"),
                            ("operations", "Operations"),
                            ("other", "Other"),
                        ],
                        default="software",
                        help_text="Type of project",
                        max_length=20,
                        verbose_name="project type",
                    ),
                ),
                (
                    "template",
                    models.CharField(
                        choices=[
                            ("scrum", "Scrum"),
                            ("kanban", "Kanban"),
                            ("basic", "Basic"),
                        ],
                        default="basic",
                        help_text="Project template/methodology",
                        max_length=20,
                        verbose_name="template",
                    ),
                ),
                (
                    "settings",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Project-specific settings (workflows, fields, permissions, etc.)",
                        verbose_name="settings",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this project is active",
                        verbose_name="is active",
                    ),
                ),
                (
                    "is_private",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this project is private (only members can see)",
                        verbose_name="is private",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        blank=True,
                        help_text="Project lead/manager",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="led_projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="Organization this project belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to="organizations.organization",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "project",
                "verbose_name_plural": "projects",
                "db_table": "projects",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProjectMember",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Timestamp when the record was soft deleted",
                        null=True,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID4)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "is_admin",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether this member is a project admin",
                        verbose_name="is admin",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this membership is active",
                        verbose_name="is active",
                    ),
                ),
                (
                    "custom_permissions",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Custom permissions for this specific member",
                        verbose_name="custom permissions",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project this membership belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_members",
                        to="projects.project",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who is a member",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "project member",
                "verbose_name_plural": "project members",
                "db_table": "project_members",
                "ordering": ["project", "user"],
            },
        ),
        migrations.AddField(
            model_name="project",
            name="members",
            field=models.ManyToManyField(
                help_text="Users who are members of this project",
                related_name="member_projects",
                through="projects.ProjectMember",
                through_fields=("project", "user"),
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="ProjectRole",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Timestamp when the record was soft deleted",
                        null=True,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID4)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Role name (e.g., Developer, Viewer, Admin)",
                        max_length=100,
                        verbose_name="name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Role description",
                        verbose_name="description",
                    ),
                ),
                (
                    "permissions",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Role permissions configuration",
                        verbose_name="permissions",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is a default role for new projects",
                        verbose_name="is default",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="Organization this role belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_roles",
                        to="organizations.organization",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "project role",
                "verbose_name_plural": "project roles",
                "db_table": "project_roles",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="projectmember",
            name="role",
            field=models.ForeignKey(
                blank=True,
                help_text="Role assigned to this member",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="members",
                to="projects.projectrole",
            ),
        ),
        migrations.CreateModel(
            name="ProjectTemplate",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Timestamp when the record was soft deleted",
                        null=True,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID4)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Template name", max_length=100, verbose_name="name"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Template description",
                        verbose_name="description",
                    ),
                ),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("scrum", "Scrum"),
                            ("kanban", "Kanban"),
                            ("basic", "Basic"),
                        ],
                        default="basic",
                        help_text="Template type",
                        max_length=20,
                        verbose_name="template type",
                    ),
                ),
                (
                    "config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Template configuration (default settings, roles, workflows, etc.)",
                        verbose_name="configuration",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is the default template",
                        verbose_name="is default",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="Organization this template belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_templates",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "project template",
                "verbose_name_plural": "project templates",
                "db_table": "project_templates",
                "ordering": ["name"],
            },
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["organization", "key"], name="projects_organiz_ecd33c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["organization", "is_active"], name="projects_organiz_24f550_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["is_active", "name"], name="projects_is_acti_70706d_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="project",
            unique_together={("organization", "key")},
        ),
        migrations.AddIndex(
            model_name="projectrole",
            index=models.Index(
                fields=["organization", "name"], name="project_rol_organiz_5e91aa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="projectrole",
            index=models.Index(
                fields=["organization", "is_default"],
                name="project_rol_organiz_618808_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="projectrole",
            unique_together={("organization", "name")},
        ),
        migrations.AddIndex(
            model_name="projectmember",
            index=models.Index(
                fields=["project", "user"], name="project_mem_project_9e0a06_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="projectmember",
            index=models.Index(
                fields=["project", "is_active"], name="project_mem_project_bd103d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="projectmember",
            index=models.Index(
                fields=["user", "is_active"], name="project_mem_user_id_977694_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="projectmember",
            index=models.Index(
                fields=["project", "is_admin", "is_active"],
                name="project_mem_project_d53595_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="projectmember",
            unique_together={("project", "user")},
        ),
        migrations.AddIndex(
            model_name="projecttemplate",
            index=models.Index(
                fields=["organization", "is_default"],
                name="project_tem_organiz_3b5809_idx",
            ),
        ),
    ]
