# Generated by Django 5.2.5 on 2026-02-15 05:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Status",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Timestamp when the record was soft deleted",
                        null=True,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID4)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Status name (e.g., Open, In Progress, Done)",
                        max_length=100,
                        verbose_name="name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Status description",
                        verbose_name="description",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("todo", "To Do"),
                            ("in_progress", "In Progress"),
                            ("done", "Done"),
                        ],
                        db_index=True,
                        default="todo",
                        help_text="Status category for grouping",
                        max_length=20,
                        verbose_name="category",
                    ),
                ),
                (
                    "is_initial",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is the initial status for new issues",
                        verbose_name="is initial",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this status is active",
                        verbose_name="is active",
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Display order within workflow",
                        verbose_name="position",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "status",
                "verbose_name_plural": "statuses",
                "db_table": "workflow_statuses",
                "ordering": ["workflow", "position", "name"],
            },
        ),
        migrations.CreateModel(
            name="Workflow",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Timestamp when the record was soft deleted",
                        null=True,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID4)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Workflow name (e.g., Simple Workflow, Scrum Workflow)",
                        max_length=100,
                        verbose_name="name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Workflow description",
                        verbose_name="description",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this workflow is active",
                        verbose_name="is active",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is the default workflow for new projects",
                        verbose_name="is default",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="Organization this workflow belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workflows",
                        to="organizations.organization",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "workflow",
                "verbose_name_plural": "workflows",
                "db_table": "workflows",
                "ordering": ["organization", "name"],
            },
        ),
        migrations.CreateModel(
            name="Transition",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Timestamp when the record was soft deleted",
                        null=True,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID4)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Transition name (e.g., Start Progress, Resolve, Close)",
                        max_length=100,
                        verbose_name="name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Transition description",
                        verbose_name="description",
                    ),
                ),
                (
                    "conditions",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Conditions that must be met (e.g., user in role, field has value)",
                        verbose_name="conditions",
                    ),
                ),
                (
                    "validators",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Validation rules (e.g., field required, resolution required)",
                        verbose_name="validators",
                    ),
                ),
                (
                    "post_functions",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Actions to execute after transition (e.g., assign to user, send email)",
                        verbose_name="post_functions",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this transition is active",
                        verbose_name="is active",
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Display order in UI",
                        verbose_name="position",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "from_status",
                    models.ForeignKey(
                        blank=True,
                        help_text="Source status (null for initial transition)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_transitions",
                        to="workflows.status",
                    ),
                ),
                (
                    "to_status",
                    models.ForeignKey(
                        help_text="Destination status",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_transitions",
                        to="workflows.status",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        help_text="Workflow this transition belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transitions",
                        to="workflows.workflow",
                    ),
                ),
            ],
            options={
                "verbose_name": "transition",
                "verbose_name_plural": "transitions",
                "db_table": "workflow_transitions",
                "ordering": ["workflow", "position", "name"],
            },
        ),
        migrations.AddField(
            model_name="status",
            name="workflow",
            field=models.ForeignKey(
                help_text="Workflow this status belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="statuses",
                to="workflows.workflow",
            ),
        ),
        migrations.CreateModel(
            name="WorkflowScheme",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Timestamp when the record was soft deleted",
                        null=True,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID4)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Scheme name", max_length=100, verbose_name="name"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Scheme description",
                        verbose_name="description",
                    ),
                ),
                (
                    "mappings",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Issue type to workflow mappings",
                        verbose_name="mappings",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this scheme is active",
                        verbose_name="is active",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "default_workflow",
                    models.ForeignKey(
                        help_text="Default workflow for unmapped issue types",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="default_for_schemes",
                        to="workflows.workflow",
                    ),
                ),
                (
                    "project",
                    models.OneToOneField(
                        help_text="Project this scheme belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workflow_scheme",
                        to="projects.project",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "workflow scheme",
                "verbose_name_plural": "workflow schemes",
                "db_table": "workflow_schemes",
                "ordering": ["project", "name"],
            },
        ),
        migrations.AddIndex(
            model_name="workflow",
            index=models.Index(
                fields=["organization", "name"], name="workflows_organiz_c345a1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workflow",
            index=models.Index(
                fields=["organization", "is_active"],
                name="workflows_organiz_5ab487_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="workflow",
            index=models.Index(
                fields=["organization", "is_default"],
                name="workflows_organiz_a9dfea_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="workflow",
            unique_together={("organization", "name")},
        ),
        migrations.AddIndex(
            model_name="transition",
            index=models.Index(
                fields=["workflow", "from_status"],
                name="workflow_tr_workflo_f5bdae_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="transition",
            index=models.Index(
                fields=["workflow", "to_status"], name="workflow_tr_workflo_f504cd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transition",
            index=models.Index(
                fields=["workflow", "is_active"], name="workflow_tr_workflo_549a69_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transition",
            index=models.Index(
                fields=["from_status", "to_status"],
                name="workflow_tr_from_st_401acb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="status",
            index=models.Index(
                fields=["workflow", "name"], name="workflow_st_workflo_57ee6c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="status",
            index=models.Index(
                fields=["workflow", "category"], name="workflow_st_workflo_642025_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="status",
            index=models.Index(
                fields=["workflow", "is_initial"], name="workflow_st_workflo_cc857b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="status",
            index=models.Index(
                fields=["workflow", "position"], name="workflow_st_workflo_f76cbc_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="status",
            unique_together={("workflow", "name")},
        ),
        migrations.AddIndex(
            model_name="workflowscheme",
            index=models.Index(
                fields=["project", "is_active"], name="workflow_sc_project_2585c1_idx"
            ),
        ),
    ]
