# Generated by Django 5.2.5 on 2026-02-15 09:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("issues", "0001_initial"),
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Board",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Timestamp when the record was soft deleted",
                        null=True,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID4)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Board name", max_length=100, verbose_name="name"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Board description",
                        verbose_name="description",
                    ),
                ),
                (
                    "board_type",
                    models.CharField(
                        choices=[("scrum", "Scrum"), ("kanban", "Kanban")],
                        default="scrum",
                        help_text="Type of board (Scrum or Kanban)",
                        max_length=20,
                        verbose_name="board type",
                    ),
                ),
                (
                    "column_config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Column configuration (status to column mapping)",
                        verbose_name="column configuration",
                    ),
                ),
                (
                    "swimlane_config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Swimlane configuration (grouping strategy)",
                        verbose_name="swimlane configuration",
                    ),
                ),
                (
                    "quick_filters",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Quick filter definitions (JQL-like queries)",
                        verbose_name="quick filters",
                    ),
                ),
                (
                    "filter_query",
                    models.TextField(
                        blank=True,
                        help_text="JQL-like query to filter issues on this board",
                        verbose_name="filter query",
                    ),
                ),
                (
                    "estimation_field",
                    models.CharField(
                        blank=True,
                        help_text='Field used for estimations (e.g., "story_points")',
                        max_length=100,
                        verbose_name="estimation field",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this board is active",
                        verbose_name="is active",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project this board belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="boards",
                        to="projects.project",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "board",
                "verbose_name_plural": "boards",
                "db_table": "boards",
                "ordering": ["project", "name"],
            },
        ),
        migrations.CreateModel(
            name="BoardIssue",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Timestamp when the record was soft deleted",
                        null=True,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID4)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "rank",
                    models.IntegerField(
                        db_index=True,
                        default=0,
                        help_text="Issue rank/position on the board (for ordering)",
                        verbose_name="rank",
                    ),
                ),
                (
                    "board",
                    models.ForeignKey(
                        help_text="Board",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="board_issues",
                        to="boards.board",
                    ),
                ),
                (
                    "issue",
                    models.ForeignKey(
                        help_text="Issue",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="board_issues",
                        to="issues.issue",
                    ),
                ),
            ],
            options={
                "verbose_name": "board issue",
                "verbose_name_plural": "board issues",
                "db_table": "board_issues",
                "ordering": ["board", "rank"],
            },
        ),
        migrations.CreateModel(
            name="Sprint",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Timestamp when the record was soft deleted",
                        null=True,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID4)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Sprint name", max_length=100, verbose_name="name"
                    ),
                ),
                (
                    "goal",
                    models.TextField(
                        blank=True,
                        help_text="Sprint goal/objective",
                        verbose_name="goal",
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Sprint start date",
                        null=True,
                        verbose_name="start date",
                    ),
                ),
                (
                    "end_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Sprint end date",
                        null=True,
                        verbose_name="end date",
                    ),
                ),
                (
                    "completed_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date when sprint was completed",
                        null=True,
                        verbose_name="completed date",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("future", "Future"),
                            ("active", "Active"),
                            ("closed", "Closed"),
                        ],
                        db_index=True,
                        default="future",
                        help_text="Sprint state",
                        max_length=20,
                        verbose_name="state",
                    ),
                ),
                (
                    "board",
                    models.ForeignKey(
                        help_text="Board this sprint belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sprints",
                        to="boards.board",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "issues",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Issues in this sprint",
                        related_name="sprints",
                        to="issues.issue",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "sprint",
                "verbose_name_plural": "sprints",
                "db_table": "sprints",
                "ordering": ["board", "-start_date"],
            },
        ),
        migrations.AddIndex(
            model_name="board",
            index=models.Index(
                fields=["project", "board_type"], name="boards_project_70e431_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="board",
            index=models.Index(
                fields=["project", "is_active"], name="boards_project_4d58d7_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="board",
            unique_together={("project", "name")},
        ),
        migrations.AddIndex(
            model_name="boardissue",
            index=models.Index(
                fields=["board", "rank"], name="board_issue_board_i_598c2b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="boardissue",
            index=models.Index(fields=["issue"], name="board_issue_issue_i_3564d0_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="boardissue",
            unique_together={("board", "issue")},
        ),
        migrations.AddIndex(
            model_name="sprint",
            index=models.Index(
                fields=["board", "state"], name="sprints_board_i_d37e6a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sprint",
            index=models.Index(
                fields=["board", "-start_date"], name="sprints_board_i_c8f16a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sprint",
            index=models.Index(
                fields=["state", "start_date"], name="sprints_state_0e3408_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="sprint",
            unique_together={("board", "name")},
        ),
    ]
