# Generated by Django 5.2.5 on 2026-02-15 09:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
        ("projects", "0001_initial"),
        ("workflows", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Issue",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Timestamp when the record was soft deleted",
                        null=True,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID4)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        db_index=True,
                        help_text="Unique issue key (e.g., PROJ-123)",
                        max_length=50,
                        unique=True,
                        verbose_name="key",
                    ),
                ),
                (
                    "summary",
                    models.CharField(
                        help_text="Issue summary/title",
                        max_length=500,
                        verbose_name="summary",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Detailed description",
                        verbose_name="description",
                    ),
                ),
                (
                    "original_estimate",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Original time estimate in minutes",
                        null=True,
                        verbose_name="original estimate",
                    ),
                ),
                (
                    "remaining_estimate",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Remaining time estimate in minutes",
                        null=True,
                        verbose_name="remaining estimate",
                    ),
                ),
                (
                    "time_spent",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Time spent in minutes",
                        verbose_name="time spent",
                    ),
                ),
                (
                    "due_date",
                    models.DateField(
                        blank=True,
                        help_text="Due date for this issue",
                        null=True,
                        verbose_name="due date",
                    ),
                ),
                (
                    "resolution_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the issue was resolved",
                        null=True,
                        verbose_name="resolution date",
                    ),
                ),
                (
                    "resolution",
                    models.CharField(
                        blank=True,
                        help_text="Resolution (e.g., Fixed, Won't Fix, Duplicate)",
                        max_length=100,
                        verbose_name="resolution",
                    ),
                ),
                (
                    "custom_field_values",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Dynamic custom field values",
                        verbose_name="custom field values",
                    ),
                ),
                (
                    "assignee",
                    models.ForeignKey(
                        blank=True,
                        help_text="User assigned to this issue",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_issues",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "epic",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent epic",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="epic_children",
                        to="issues.issue",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent issue (for subtasks)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subtasks",
                        to="issues.issue",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project this issue belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="issues",
                        to="projects.project",
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        help_text="User who reported this issue",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reported_issues",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        help_text="Current status",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="issues",
                        to="workflows.status",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "issue",
                "verbose_name_plural": "issues",
                "db_table": "issues",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="IssueLinkType",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Timestamp when the record was soft deleted",
                        null=True,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID4)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Link type name (e.g., blocks, relates to)",
                        max_length=100,
                        verbose_name="name",
                    ),
                ),
                (
                    "inward_description",
                    models.CharField(
                        help_text='Description from target to source (e.g., "is blocked by")',
                        max_length=100,
                        verbose_name="inward description",
                    ),
                ),
                (
                    "outward_description",
                    models.CharField(
                        help_text='Description from source to target (e.g., "blocks")',
                        max_length=100,
                        verbose_name="outward description",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this link type is active",
                        verbose_name="is active",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="Organization this link type belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="issue_link_types",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "issue link type",
                "verbose_name_plural": "issue link types",
                "db_table": "issue_link_types",
                "ordering": ["organization", "name"],
            },
        ),
        migrations.CreateModel(
            name="IssueLink",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Timestamp when the record was soft deleted",
                        null=True,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID4)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "from_issue",
                    models.ForeignKey(
                        help_text="Source issue",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outward_links",
                        to="issues.issue",
                    ),
                ),
                (
                    "to_issue",
                    models.ForeignKey(
                        help_text="Target issue",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inward_links",
                        to="issues.issue",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "link_type",
                    models.ForeignKey(
                        help_text="Type of relationship",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="links",
                        to="issues.issuelinktype",
                    ),
                ),
            ],
            options={
                "verbose_name": "issue link",
                "verbose_name_plural": "issue links",
                "db_table": "issue_links",
                "ordering": ["from_issue", "link_type"],
            },
        ),
        migrations.CreateModel(
            name="IssueType",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Timestamp when the record was soft deleted",
                        null=True,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID4)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Issue type name (e.g., Story, Task, Bug, Epic)",
                        max_length=100,
                        verbose_name="name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Issue type description",
                        verbose_name="description",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Icon identifier for UI",
                        max_length=50,
                        verbose_name="icon",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True,
                        help_text="Color hex code (e.g., #FF5733)",
                        max_length=7,
                        verbose_name="color",
                    ),
                ),
                (
                    "is_subtask",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is a subtask type",
                        verbose_name="is subtask",
                    ),
                ),
                (
                    "is_epic",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is an epic type",
                        verbose_name="is epic",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is the default issue type",
                        verbose_name="is default",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this issue type is active",
                        verbose_name="is active",
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        default=0, help_text="Display order", verbose_name="position"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="Organization this issue type belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="issue_types",
                        to="organizations.organization",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "issue type",
                "verbose_name_plural": "issue types",
                "db_table": "issue_types",
                "ordering": ["organization", "position", "name"],
            },
        ),
        migrations.AddField(
            model_name="issue",
            name="issue_type",
            field=models.ForeignKey(
                help_text="Issue type",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="issues",
                to="issues.issuetype",
            ),
        ),
        migrations.CreateModel(
            name="Label",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Timestamp when the record was soft deleted",
                        null=True,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID4)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Label name", max_length=100, verbose_name="name"
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True,
                        help_text="Color hex code",
                        max_length=7,
                        verbose_name="color",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="Organization this label belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="labels",
                        to="organizations.organization",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        help_text="Project this label belongs to (null for org-wide)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="labels",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "label",
                "verbose_name_plural": "labels",
                "db_table": "labels",
                "ordering": ["organization", "name"],
            },
        ),
        migrations.AddField(
            model_name="issue",
            name="labels",
            field=models.ManyToManyField(
                blank=True,
                help_text="Issue labels/tags",
                related_name="issues",
                to="issues.label",
            ),
        ),
        migrations.CreateModel(
            name="Priority",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Timestamp when the record was soft deleted",
                        null=True,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID4)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Priority name (e.g., Blocker, High, Medium, Low)",
                        max_length=100,
                        verbose_name="name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Priority description",
                        verbose_name="description",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Icon identifier for UI",
                        max_length=50,
                        verbose_name="icon",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True,
                        help_text="Color hex code (e.g., #FF0000)",
                        max_length=7,
                        verbose_name="color",
                    ),
                ),
                (
                    "level",
                    models.PositiveIntegerField(
                        default=3,
                        help_text="Priority level (1=highest, 5=lowest)",
                        verbose_name="level",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is the default priority",
                        verbose_name="is default",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this priority is active",
                        verbose_name="is active",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="Organization this priority belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="priorities",
                        to="organizations.organization",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "priority",
                "verbose_name_plural": "priorities",
                "db_table": "priorities",
                "ordering": ["organization", "level", "name"],
            },
        ),
        migrations.AddField(
            model_name="issue",
            name="priority",
            field=models.ForeignKey(
                blank=True,
                help_text="Issue priority",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="issues",
                to="issues.priority",
            ),
        ),
        migrations.CreateModel(
            name="Watcher",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Timestamp when the record was soft deleted",
                        null=True,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID4)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "issue",
                    models.ForeignKey(
                        help_text="Issue being watched",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="watchers",
                        to="issues.issue",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User watching the issue",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="watched_issues",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "watcher",
                "verbose_name_plural": "watchers",
                "db_table": "issue_watchers",
                "ordering": ["issue", "user"],
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Timestamp when the record was soft deleted",
                        null=True,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID4)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        help_text="Comment text (supports markdown)",
                        verbose_name="body",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "mentions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Users mentioned in this comment",
                        related_name="mentioned_in_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who made this comment",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="issue_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "issue",
                    models.ForeignKey(
                        help_text="Issue this comment belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="issues.issue",
                    ),
                ),
            ],
            options={
                "verbose_name": "comment",
                "verbose_name_plural": "comments",
                "db_table": "issue_comments",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["issue", "created_at"],
                        name="issue_comme_issue_i_937053_idx",
                    ),
                    models.Index(
                        fields=["user", "created_at"],
                        name="issue_comme_user_id_f33182_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Timestamp when the record was soft deleted",
                        null=True,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID4)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Uploaded file",
                        upload_to="issue_attachments/%Y/%m/%d/",
                        verbose_name="file",
                    ),
                ),
                (
                    "filename",
                    models.CharField(
                        help_text="Original filename",
                        max_length=255,
                        verbose_name="filename",
                    ),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        help_text="File size in bytes", verbose_name="file size"
                    ),
                ),
                (
                    "mime_type",
                    models.CharField(
                        blank=True,
                        help_text="MIME type of the file",
                        max_length=100,
                        verbose_name="mime type",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "issue",
                    models.ForeignKey(
                        help_text="Issue this attachment belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="issues.issue",
                    ),
                ),
            ],
            options={
                "verbose_name": "attachment",
                "verbose_name_plural": "attachments",
                "db_table": "issue_attachments",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["issue", "-created_at"],
                        name="issue_attac_issue_i_b82da9_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="issuelinktype",
            index=models.Index(
                fields=["organization", "name"], name="issue_link__organiz_664093_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="issuelinktype",
            unique_together={("organization", "name")},
        ),
        migrations.AddIndex(
            model_name="issuelink",
            index=models.Index(
                fields=["from_issue", "link_type"],
                name="issue_links_from_is_6324dc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="issuelink",
            index=models.Index(
                fields=["to_issue", "link_type"], name="issue_links_to_issu_165eff_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="issuelink",
            unique_together={("from_issue", "to_issue", "link_type")},
        ),
        migrations.AddIndex(
            model_name="issuetype",
            index=models.Index(
                fields=["organization", "name"], name="issue_types_organiz_254dc9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="issuetype",
            index=models.Index(
                fields=["organization", "is_active"],
                name="issue_types_organiz_4aab6a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="issuetype",
            index=models.Index(
                fields=["organization", "is_default"],
                name="issue_types_organiz_4b294a_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="issuetype",
            unique_together={("organization", "name")},
        ),
        migrations.AddIndex(
            model_name="label",
            index=models.Index(
                fields=["organization", "name"], name="labels_organiz_835665_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="label",
            index=models.Index(
                fields=["project", "name"], name="labels_project_a9ecc6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="priority",
            index=models.Index(
                fields=["organization", "name"], name="priorities_organiz_a1bd46_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="priority",
            index=models.Index(
                fields=["organization", "level"], name="priorities_organiz_06c64b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="priority",
            index=models.Index(
                fields=["organization", "is_default"],
                name="priorities_organiz_db42e6_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="priority",
            unique_together={("organization", "name")},
        ),
        migrations.AddIndex(
            model_name="issue",
            index=models.Index(
                fields=["project", "key"], name="issues_project_2bc950_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="issue",
            index=models.Index(
                fields=["project", "status"], name="issues_project_ba36b7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="issue",
            index=models.Index(
                fields=["project", "issue_type"], name="issues_project_4ccf46_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="issue",
            index=models.Index(
                fields=["project", "assignee"], name="issues_project_e4335b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="issue",
            index=models.Index(
                fields=["project", "reporter"], name="issues_project_3019e1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="issue",
            index=models.Index(
                fields=["assignee", "status"], name="issues_assigne_8acd4b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="issue",
            index=models.Index(fields=["epic"], name="issues_epic_id_2c4ae8_idx"),
        ),
        migrations.AddIndex(
            model_name="issue",
            index=models.Index(fields=["parent"], name="issues_parent__3eb5f1_idx"),
        ),
        migrations.AddIndex(
            model_name="issue",
            index=models.Index(fields=["due_date"], name="issues_due_dat_f0f017_idx"),
        ),
        migrations.AddIndex(
            model_name="issue",
            index=models.Index(
                fields=["-created_at"], name="issues_created_8bcb8f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="watcher",
            index=models.Index(fields=["issue"], name="issue_watch_issue_i_fca95c_idx"),
        ),
        migrations.AddIndex(
            model_name="watcher",
            index=models.Index(fields=["user"], name="issue_watch_user_id_29fb11_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="watcher",
            unique_together={("issue", "user")},
        ),
    ]
