# Generated by Django 5.2.5 on 2026-02-15 10:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("issues", "0001_initial"),
        ("organizations", "0001_initial"),
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AutomationRule",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Timestamp when the record was soft deleted",
                        null=True,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID4)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Rule name", max_length=200, verbose_name="name"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Rule description",
                        verbose_name="description",
                    ),
                ),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[
                            ("issue_created", "Issue Created"),
                            ("issue_updated", "Issue Updated"),
                            ("field_changed", "Field Value Changed"),
                            ("issue_transitioned", "Issue Transitioned"),
                            ("issue_assigned", "Issue Assigned"),
                            ("comment_added", "Comment Added"),
                            ("scheduled", "Scheduled (Cron)"),
                        ],
                        db_index=True,
                        help_text="Type of trigger that activates this rule",
                        max_length=50,
                        verbose_name="trigger type",
                    ),
                ),
                (
                    "trigger_config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Trigger-specific configuration (e.g., which field changed)",
                        verbose_name="trigger configuration",
                    ),
                ),
                (
                    "conditions",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of conditions that must be met for rule to execute",
                        verbose_name="conditions",
                    ),
                ),
                (
                    "actions",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of actions to execute when rule triggers and conditions pass",
                        verbose_name="actions",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this rule is active",
                        verbose_name="is active",
                    ),
                ),
                (
                    "execution_count",
                    models.IntegerField(
                        default=0,
                        help_text="Number of times this rule has been executed",
                        verbose_name="execution count",
                    ),
                ),
                (
                    "last_executed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this rule was last executed",
                        null=True,
                        verbose_name="last executed at",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="Organization this rule belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="automation_rules",
                        to="organizations.organization",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        help_text="Project this rule applies to (null for organization-wide)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="automation_rules",
                        to="projects.project",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "automation rule",
                "verbose_name_plural": "automation rules",
                "db_table": "automation_rules",
                "ordering": ["organization", "name"],
            },
        ),
        migrations.CreateModel(
            name="AutomationExecution",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Timestamp when the record was soft deleted",
                        null=True,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID4)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "trigger_event",
                    models.JSONField(
                        default=dict,
                        help_text="Event data that triggered this execution",
                        verbose_name="trigger event",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("partial", "Partial Success"),
                        ],
                        db_index=True,
                        help_text="Execution status",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "conditions_passed",
                    models.BooleanField(
                        default=False,
                        help_text="Whether all conditions passed",
                        verbose_name="conditions passed",
                    ),
                ),
                (
                    "conditions_result",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Result of each condition evaluation",
                        verbose_name="conditions result",
                    ),
                ),
                (
                    "actions_executed",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of actions that were executed",
                        verbose_name="actions executed",
                    ),
                ),
                (
                    "actions_result",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Result of each action execution",
                        verbose_name="actions result",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        help_text="Error message if execution failed",
                        verbose_name="error message",
                    ),
                ),
                (
                    "error_details",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Detailed error information",
                        verbose_name="error details",
                    ),
                ),
                (
                    "execution_time_ms",
                    models.IntegerField(
                        blank=True,
                        help_text="Execution time in milliseconds",
                        null=True,
                        verbose_name="execution time (ms)",
                    ),
                ),
                (
                    "issue",
                    models.ForeignKey(
                        blank=True,
                        help_text="Issue that triggered the automation (if applicable)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="automation_executions",
                        to="issues.issue",
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        help_text="Automation rule that was executed",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions",
                        to="automation.automationrule",
                    ),
                ),
            ],
            options={
                "verbose_name": "automation execution",
                "verbose_name_plural": "automation executions",
                "db_table": "automation_executions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="automationrule",
            index=models.Index(
                fields=["organization", "is_active"],
                name="automation__organiz_32d1fa_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="automationrule",
            index=models.Index(
                fields=["project", "is_active"], name="automation__project_dd6d1c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="automationrule",
            index=models.Index(
                fields=["trigger_type", "is_active"],
                name="automation__trigger_5b91da_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="automationrule",
            index=models.Index(
                fields=["organization", "trigger_type"],
                name="automation__organiz_d7404a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="automationexecution",
            index=models.Index(
                fields=["rule", "-created_at"], name="automation__rule_id_c02849_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="automationexecution",
            index=models.Index(
                fields=["issue", "-created_at"], name="automation__issue_i_301d84_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="automationexecution",
            index=models.Index(
                fields=["status", "-created_at"], name="automation__status_e30eb8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="automationexecution",
            index=models.Index(
                fields=["-created_at"], name="automation__created_adb93b_idx"
            ),
        ),
    ]
